name: docker

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
        -
            name: Checkout
            uses: actions/checkout@v5

        - 
            name: Docker meta
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: ${{ secrets.DOCKER_USERNAME }}/xiaoya-emd-go
                tags: |
                    type=raw,value=latest

        -
            name: Set Up QEMU
            uses: docker/setup-qemu-action@v3

        -
            name: Set Up Buildx
            uses: docker/setup-buildx-action@v3

        -
            name: Login DockerHub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

        -
            name: Build Image
            uses: docker/build-push-action@v6
            with:
                context: .
                file: Dockerfile
                platforms: |
                    linux/amd64
                    linux/arm64/v8
                    linux/arm/v7
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
            env:
                DOCKER_BUILD_RECORD_UPLOAD: false

        - 
            name: Docker Hub Description
            uses: peter-evans/dockerhub-description@v4
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: ${{ secrets.DOCKER_USERNAME }}/xiaoya-emd-go
                short-description: 小雅元数据爬虫Golang版
                readme-filepath: README.md
